name: SamoSoviet/Experiment
author:
  name: Samo Soviet
  email: SamoSoviet@hotmail.com
  url: 'http://samosoviet.com/'
copyright: 2015 Samo Soviet
description: This is experiment project - Solar System
